Repository AgileFrontend/AgileFrontend, pull requests merged in 2023-11, with the labels that each got.

#26 Dev home page team3
  AgileFront/src/app/app-routing.module.ts
  AgileFront/src/app/app.component.html
  AgileFront/src/app/app.module.ts
  AgileFront/src/app/homepage/homepage.component.html
  AgileFront/src/app/homepage/homepage.component.scss
  AgileFront/src/app/homepage/homepage.component.spec.ts
  AgileFront/src/app/homepage/homepage.component.ts
  AgileFront/src/app/navbar/navbar.component.html
  AgileFront/src/app/navbar/navbar.component.scss
  AgileFront/src/app/navbar/navbar.component.spec.ts
  AgileFront/src/app/navbar/navbar.component.ts
Labels: Team 3

#32 PR to merge register component and service into dev
  AgileFront/src/app/app-routing.module.ts
  AgileFront/src/app/app.module.ts
  AgileFront/src/app/register/register.component.html
  AgileFront/src/app/register/register.component.scss
  AgileFront/src/app/register/register.component.spec.ts
  AgileFront/src/app/register/register.component.ts
  AgileFront/src/app/services/register/register.service.spec.ts
  AgileFront/src/app/services/register/register.service.ts
Labels: Team 2

#33 Dev project team4
  AgileFront/src/app/app-routing.module.ts
  AgileFront/src/app/app.module.ts
  AgileFront/src/app/create.post/create.post.component.html
  AgileFront/src/app/create.post/create.post.component.scss
  AgileFront/src/app/create.post/create.post.component.spec.ts
  AgileFront/src/app/create.post/create.post.component.ts
  AgileFront/src/app/services/post.ts
  AgileFront/src/app/services/storage/storage.service.spec.ts
  AgileFront/src/app/services/storage/storage.service.ts
Labels: Team 4

#41 Add AuthService and AuthGuard
  AgileFront/src/app/app-routing.module.ts
  AgileFront/src/app/services/auth/auth.service.spec.ts
  AgileFront/src/app/services/auth/auth.service.ts
  AgileFront/src/app/services/user.ts
Labels: Auth

#42 Dev team1 login bug fixed
  AgileFront/package-lock.json
  AgileFront/src/app/app-routing.module.ts
  AgileFront/src/app/app.component.html
  AgileFront/src/app/homepage/homepage.component.html
  AgileFront/src/app/login/login.component.html
  AgileFront/src/app/login/login.component.scss
  AgileFront/src/app/login/login.component.ts
  AgileFront/src/app/navbar/navbar.component.html
  AgileFront/src/app/navbar/navbar.component.ts
  AgileFront/src/app/register/register.component.html
Labels: enhancement

#44 Add redirect to homepage, Modify CreateUser function
  AgileFront/src/app/register/register.component.html
  AgileFront/src/app/register/register.component.ts
  AgileFront/src/app/services/register/register.service.ts
Labels: enhancement

#48 Fix navbar reactive feature for login
  AgileFront/src/app/navbar/navbar.component.html
  AgileFront/src/app/navbar/navbar.component.scss
  AgileFront/src/app/navbar/navbar.component.ts
Labels: bug, bugfix

#49 Post.refactor dev
  AgileFront/angular.json
  AgileFront/src/app/create.post/create.post.component.html
  AgileFront/src/app/create.post/create.post.component.ts
  AgileFront/src/app/services/post.ts
  AgileFront/src/app/services/post/post.service.spec.ts
  AgileFront/src/app/services/post/post.service.ts
  AgileFront/src/app/services/storage/storage.service.ts
Labels: enhancement, Team 4, bugfix

#52 Create User in Firestore after registering and a few fixes
  AgileFront/src/app/services/auth/auth.service.ts
  AgileFront/src/app/services/post.ts
  AgileFront/src/app/services/post/post.service.ts
  AgileFront/src/app/services/register/register.service.ts
  AgileFront/src/app/services/user.ts
Labels: bug, Auth, bugfix

#53 Dev project details team3
  AgileFront/src/app/app.module.ts
  AgileFront/src/app/create.post/create.post.component.ts
  AgileFront/src/app/homepage/homepage.component.html
  AgileFront/src/app/homepage/homepage.component.scss
  AgileFront/src/app/homepage/homepage.component.ts
  AgileFront/src/app/my-project-page/my-project-page.component.html
  AgileFront/src/app/navbar/navbar.component.ts
  AgileFront/src/app/project/project.component.html
  AgileFront/src/app/project/project.component.scss
  AgileFront/src/app/project/project.component.ts
  AgileFront/src/app/services/post.ts
  AgileFront/src/app/services/post/post.service.ts
Labels: Team 3, Accessibility

#58 Dev profile page team2
  AgileFront/src/app/app-routing.module.ts
  AgileFront/src/app/app.module.ts
  AgileFront/src/app/file-upload/file-upload.component.html
  AgileFront/src/app/file-upload/file-upload.component.scss
  AgileFront/src/app/file-upload/file-upload.component.spec.ts
  AgileFront/src/app/file-upload/file-upload.component.ts
  AgileFront/src/app/navbar/navbar.component.html
  AgileFront/src/app/profile/profile.component.html
  AgileFront/src/app/profile/profile.component.scss
  AgileFront/src/app/profile/profile.component.spec.ts
  AgileFront/src/app/profile/profile.component.ts
  AgileFront/src/app/register/register.component.html
  AgileFront/src/app/services/profile/profile.service.spec.ts
  AgileFront/src/app/services/profile/profile.service.ts
  AgileFront/src/app/services/storage/storage.service.ts
Labels: enhancement, Team 2

#69 Dev display profile team2
  AgileFront/src/app/app-routing.module.ts
  AgileFront/src/app/app.module.ts
  AgileFront/src/app/display-profile/display-profile.component.html
  AgileFront/src/app/display-profile/display-profile.component.scss
  AgileFront/src/app/display-profile/display-profile.component.spec.ts
  AgileFront/src/app/display-profile/display-profile.component.ts
  AgileFront/src/app/edit-profile/edit-profile.component.html
  AgileFront/src/app/edit-profile/edit-profile.component.scss
  AgileFront/src/app/edit-profile/edit-profile.component.spec.ts
  AgileFront/src/app/edit-profile/edit-profile.component.ts
  AgileFront/src/app/navbar/navbar.component.html
  AgileFront/src/app/profile/profile.component.spec.ts
  AgileFront/src/app/services/display-profile/display-profile.service.spec.ts
  AgileFront/src/app/services/display-profile/display-profile.service.ts
  AgileFront/src/app/services/edit-profile/edit-profile.service.spec.ts
  AgileFront/src/app/services/edit-profile/edit-profile.service.ts
  AgileFront/src/app/services/post/post.service.ts
  AgileFront/src/app/services/register/register.service.ts
  AgileFront/src/app/services/user.ts
Labels: enhancement, Team 2

#79 Add link to user profile
  AgileFront/src/app/display-profile/display-profile.component.html
  AgileFront/src/app/display-profile/display-profile.component.scss
  AgileFront/src/app/display-profile/display-profile.component.ts
  AgileFront/src/app/project/project.component.html
Labels: enhancement

#78 Dev messgae
  AgileFront/angular.json
  AgileFront/karma.conf.js
  AgileFront/src/app/app-routing.module.ts
  AgileFront/src/app/app.module.ts
  AgileFront/src/app/messaging-page/conversation/conversation.component.html
  AgileFront/src/app/messaging-page/conversation/conversation.component.scss
  AgileFront/src/app/messaging-page/conversation/conversation.component.spec.ts
  AgileFront/src/app/messaging-page/conversation/conversation.component.ts
  AgileFront/src/app/messaging-page/create-message/create-message.component.html
  AgileFront/src/app/messaging-page/create-message/create-message.component.scss
  AgileFront/src/app/messaging-page/create-message/create-message.component.spec.ts
  AgileFront/src/app/messaging-page/create-message/create-message.component.ts
  AgileFront/src/app/messaging-page/message/message.component.html
  AgileFront/src/app/messaging-page/message/message.component.scss
  AgileFront/src/app/messaging-page/message/message.component.spec.ts
  AgileFront/src/app/messaging-page/message/message.component.ts
  AgileFront/src/app/messaging-page/messaging-page.component.html
  AgileFront/src/app/messaging-page/messaging-page.component.scss
  AgileFront/src/app/messaging-page/messaging-page.component.spec.ts
  AgileFront/src/app/messaging-page/messaging-page.component.ts
  AgileFront/src/app/my-project-page/my-project-page.component.ts
  AgileFront/src/app/services/conversation.ts
  AgileFront/src/app/services/instant-messaging/instant-messaging.service.ts
  AgileFront/src/app/services/message.ts
  AgileFront/src/app/services/post/post.service.ts
Labels: Team 2, Team 4, Send message to user

#85 Add icon for messaging and mics Fixs
  AgileFront/src/app/app-routing.module.ts
  AgileFront/src/app/create.post/create.post.component.html
  AgileFront/src/app/create.post/create.post.component.ts
  AgileFront/src/app/navbar/navbar.component.html
  AgileFront/src/app/navbar/navbar.component.ts
Labels: bugfix

#89 Update create-message.component.ts
  AgileFront/src/app/messaging-page/create-message/create-message.component.ts
Labels: bugfix

#91 Dev edit project component
  AgileFront/src/app/app-routing.module.ts
  AgileFront/src/app/app.module.ts
  AgileFront/src/app/edit-post/edit-post.component.html
  AgileFront/src/app/edit-post/edit-post.component.scss
  AgileFront/src/app/edit-post/edit-post.component.spec.ts
  AgileFront/src/app/edit-post/edit-post.component.ts
  AgileFront/src/app/project/project.component.html
  AgileFront/src/app/project/project.component.ts
  AgileFront/src/app/services/edit-post/edit-post.service.spec.ts
  AgileFront/src/app/services/edit-post/edit-post.service.ts
Labels: enhancement, Team 2

#93 Dev create con from profile
  AgileFront/src/app/app.module.ts
  AgileFront/src/app/display-profile/display-profile.component.html
  AgileFront/src/app/display-profile/display-profile.component.ts
  AgileFront/src/app/messaging-page/message/message.component.html
  AgileFront/src/app/messaging-page/message/message.component.ts
  AgileFront/src/app/messaging-page/messaging-page.component.html
  AgileFront/src/app/messaging-page/messaging-page.component.ts
  AgileFront/src/app/messaging-page/setting-drawer/setting-drawer.component.html
  AgileFront/src/app/messaging-page/setting-drawer/setting-drawer.component.scss
  AgileFront/src/app/messaging-page/setting-drawer/setting-drawer.component.spec.ts
  AgileFront/src/app/messaging-page/setting-drawer/setting-drawer.component.ts
  AgileFront/src/app/services/instant-messaging/instant-messaging.service.ts
Labels: Team 4
